// Ol3-Cesium. See https://github.com/openlayers/ol3-cesium/
// License: https://github.com/openlayers/ol3-cesium/blob/master/LICENSE
// Version: v1.5-34-gf1b3874

(function(){var l,m=this;function n(a){return void 0!==a}
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"array"==p(a)}function aa(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function ba(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function t(a){return a[ca]||(a[ca]=++da)}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return u.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function v(a,b){var c=a.split("."),d=m;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}function w(a,b){function c(){}c.prototype=b.prototype;a.qa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.sa=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(x,Error);x.prototype.name="CustomError";function ha(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")}function ia(a){if(!ja.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ka,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(la,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ma,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(na,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(oa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(pa,"&#0;"));return a}
var ka=/&/g,la=/</g,ma=/>/g,na=/"/g,oa=/'/g,pa=/\x00/g,ja=/[\x00&<>"']/;function qa(a,b){return a<b?-1:a>b?1:0};function ra(a,b){b.unshift(a);x.call(this,ha.apply(null,b));b.shift()}w(ra,x);ra.prototype.name="AssertionError";function y(a,b){throw new ra("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var z=Array.prototype;function A(a,b,c){z.forEach.call(a,b,c)}function sa(a,b){var c=z.indexOf.call(a,b,void 0),d;(d=0<=c)&&z.splice.call(a,c,1);return d}function ta(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var B;a:{var ua=m.navigator;if(ua){var va=ua.userAgent;if(va){B=va;break a}}B=""}function C(a){return-1!=B.indexOf(a)};function wa(){return m.navigator||null}var xa=C("Opera")||C("OPR"),E=C("Trident")||C("MSIE"),F=C("Gecko")&&-1==B.toLowerCase().indexOf("webkit")&&!(C("Trident")||C("MSIE")),H=-1!=B.toLowerCase().indexOf("webkit");H&&C("Mobile");var ya,za=wa();ya=za&&za.platform||"";ya.indexOf("Mac");ya.indexOf("Win");ya.indexOf("Linux");wa()&&(wa().appVersion||"").indexOf("X11");var I=B;I&&I.indexOf("Android");I&&I.indexOf("iPhone");I&&I.indexOf("iPad");
function Aa(){var a=m.document;return a?a.documentMode:void 0}var Ba=function(){var a="",b;if(xa&&m.opera)return a=m.opera.version,"function"==p(a)?a():a;F?b=/rv\:([^\);]+)(\)|;)/:E?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:H&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(B))?a[1]:"");return E&&(b=Aa(),b>parseFloat(a))?String(b):a}(),Ca={};
function J(a){var b;if(!(b=Ca[a])){b=0;for(var c=String(Ba).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var G=k.exec(g)||["","",""],D=r.exec(h)||["","",""];if(0==G[0].length&&0==D[0].length)break;b=qa(0==G[1].length?0:parseInt(G[1],10),0==D[1].length?0:parseInt(D[1],10))||qa(0==G[2].length,0==D[2].length)||
qa(G[2],D[2])}while(0==b)}b=Ca[a]=0<=b}return b}var Da=m.document,Ea=Da&&E?Aa()||("CSS1Compat"==Da.compatMode?parseInt(Ba,10):5):void 0;var Fa=!E||E&&9<=Ea,Ga=E&&!J("9");!H||J("528");F&&J("1.9b")||E&&J("8")||xa&&J("9.5")||H&&J("528");F&&!J("8")||E&&J("9");function Ha(){0!=Ia&&t(this)}var Ia=0;function K(a,b){this.type=a;this.a=this.target=b}K.prototype.b=function(){};function Ja(a){Ja[" "](a);return a}Ja[" "]=function(){};function L(a,b){K.call(this,a?a.type:"");this.d=this.state=this.a=this.target=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&F)try{Ja(c.nodeName)}catch(d){}this.state=a.state;this.d=a;a.defaultPrevented&&this.b()}}w(L,K);L.prototype.b=function(){L.qa.b.call(this);var a=this.d;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ga)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var M="closure_listenable_"+(1E6*Math.random()|0),Ka=0;function La(a,b,c,d,e){this.p=a;this.proxy=null;this.src=b;this.type=c;this.F=!!d;this.G=e;++Ka;this.v=this.D=!1}function Ma(a){a.v=!0;a.p=null;a.proxy=null;a.src=null;a.G=null};function Na(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Oa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Pa(a){var b={},c;for(c in a)b[c]=a[c];return b}function Qa(a){var b={},c;for(c in a)b[a[c]]=c;return b}var Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Sa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ra.length;f++)c=Ra[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function N(a){this.src=a;this.a={};this.b=0}N.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Ta(a,b,d,e);-1<g?(b=a[g],c||(b.D=!1)):(b=new La(b,this.src,f,!!d,e),b.D=c,a.push(b));return b};N.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Ta(e,b,c,d);return-1<b?(Ma(e[b]),z.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function Ua(a,b){var c=b.type;c in a.a&&sa(a.a[c],b)&&(Ma(b),0==a.a[c].length&&(delete a.a[c],a.b--))}function Ta(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.v&&f.p==b&&f.F==!!c&&f.G==d)return e}return-1};var Va="closure_lm_"+(1E6*Math.random()|0),Wa={},Xa=0;function Ya(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)Ya(a,b[f],c,d,e);return null}c=Za(c);return a&&a[M]?a.h(b,c,d,e):$a(a,b,c,!1,d,e)}function $a(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=ab(a);h||(a[Va]=h=new N(a));c=h.add(b,c,d,e,f);if(c.proxy)return c;d=bb();c.proxy=d;d.src=a;d.p=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(cb(b.toString()),d);Xa++;return c}
function bb(){var a=db,b=Fa?function(c){return a.call(b.src,b.p,c)}:function(c){c=a.call(b.src,b.p,c);if(!c)return c};return b}function eb(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)eb(a,b[f],c,d,e);else c=Za(c),a&&a[M]?a.u.add(String(b),c,!0,d,e):$a(a,b,c,!0,d,e)}function fb(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)fb(a,b[f],c,d,e);else(c=Za(c),a&&a[M])?a.u.remove(String(b),c,d,e):a&&(a=ab(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Ta(b,c,!!d,e)),(c=-1<a?b[a]:null)&&ib(c))}
function ib(a){if("number"!=typeof a&&a&&!a.v){var b=a.src;if(b&&b[M])Ua(b.u,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.F):b.detachEvent&&b.detachEvent(cb(c),d);Xa--;(c=ab(b))?(Ua(c,a),0==c.b&&(c.src=null,b[Va]=null)):Ma(a)}}}function cb(a){return a in Wa?Wa[a]:Wa[a]="on"+a}function jb(a,b,c,d){var e=1;if(a=ab(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.F==c&&!f.v&&(e&=!1!==kb(f,d))}return Boolean(e)}
function kb(a,b){var c=a.p,d=a.G||a.src;a.D&&ib(a);return c.call(d,b)}
function db(a,b){if(a.v)return!0;if(!Fa){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new L(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--)c.a=e[h],d&=jb(e[h],f,!0,c);for(h=0;h<e.length;h++)c.a=e[h],d&=jb(e[h],f,!1,c)}return d}return kb(a,
new L(b,this))}function ab(a){a=a[Va];return a instanceof N?a:null}var lb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Za(a){return"function"==p(a)?a:a[lb]||(a[lb]=function(b){return a.handleEvent(b)})};function O(a,b){this.map=a;this.e=null;this.scene=b;this.b=null;this.h=[];this.o={};this.d={};this.f=this.g=null;this.map.on("change:view",function(){this.C(this.map.getView())},this);this.C(this.map.getView());this.map.on("change:layergroup",function(){mb(this,this.map.getLayers())},this);mb(this,this.map.getLayers())}O.prototype.C=function(a){this.e=a;nb(this);this.q()};
function mb(a,b){null===a.b||A(a.h,a.b.unByKey);a.b=b;if(null===b)a.h=[];else{var c=u(function(){this.q()},a);a.h=[b.on("add",c),b.on("remove",c)]}nb(a);a.q()}O.prototype.q=function(){null!==this.e&&null!==this.b&&(this.g=Pa(this.d),this.f=Qa(this.o),this.k(!1),this.b.forEach(function(a){ob(this,a)},this),A(Oa(this.f),function(a){var b=this.o[a];n(b)&&(delete this.o[a],null===b||this.S(b))},this),this.f=null,Na(this.g,function(a,b){A(a,this.map.unByKey);delete this.d[b]},this),this.g=null)};
function ob(a,b){if(null!==b){var c=t(b);if(b instanceof ol.layer.Group){var d=b.getLayers();n(d)&&d.forEach(function(a){ob(this,a)},a);if(!n(a.d[c])){var e=[];a.d[c]=e;var f,g=[],h=u(function(){f=b.getLayers();if(n(f)){var a=u(function(){this.q()},this);g=[f.on("add",a),f.on("remove",a)];e.push.apply(e,g)}},a);h();e.push(b.on("change:layers",function(){A(g,function(a){sa(e,a);f.unByKey(a)});h()}))}delete a.g[c]}else b instanceof ol.layer.Layer&&(d=a.o[c],n(d)||(d=a.R(b),a.o[c]=d),null!=d&&(a.l(d),
delete a.f[d]))}}function nb(a){a.k(!0);a.o={}};function pb(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};function P(a,b,c){Ha.call(this);this.h=a;this.g=c;this.b=b||window;this.d=u(this.f,this)}w(P,Ha);P.prototype.a=null;P.prototype.e=!1;P.prototype.start=function(){qb(this);this.e=!1;var a=rb(this),b=sb(this);a&&!b&&this.b.mozRequestAnimationFrame?(this.a=Ya(this.b,"MozBeforePaint",this.d),this.b.mozRequestAnimationFrame(null),this.e=!0):this.a=a&&b?a.call(this.b,this.d):this.b.setTimeout(pb(this.d),20)};
function qb(a){if(null!=a.a){var b=rb(a),c=sb(a);b&&!c&&a.b.mozRequestAnimationFrame?ib(a.a):b&&c?c.call(a.b,a.a):a.b.clearTimeout(a.a)}a.a=null}P.prototype.f=function(){this.e&&this.a&&ib(this.a);this.a=null;this.h.call(this.g,ga())};function rb(a){a=a.b;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||null}
function sb(a){a=a.b;return a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||null};function Q(a,b){this.a=a;this.b=null;this.k=n(b)?b:null;this.f=!1;this.h=new Cesium.Event;this.d=document.createElement(tb);this.d.width=1;this.d.height=1;this.a.on("change",function(){ub(this)},this);ub(this)}w(Q,Cesium.ImageryProvider);
Object.defineProperties(Q.prototype,{ready:{get:function(){return this.f}},rectangle:{get:function(){return this.l}},tileWidth:{get:function(){var a=this.a.getTileGrid();return null===a?256:a.getTileSize(0)}},tileHeight:{get:function(){return this.tileWidth}},maximumLevel:{get:function(){var a=this.a.getTileGrid();return null===a?18:a.getMaxZoom()}},minimumLevel:{get:function(){return 0}},tilingScheme:{get:function(){return this.e}},tileDiscardPolicy:{get:function(){}},errorEvent:{get:function(){return this.h}},
credit:{get:function(){return this.g}},proxy:{get:function(){}},hasAlphaChannel:{get:function(){return!0}}});function ub(a){if(!a.f&&"ready"==a.a.getState()){var b=a.a.getProjection();a.b=null!=b?b:a.k;if(a.b==ol.proj.get("EPSG:4326"))a.e=new Cesium.GeographicTilingScheme;else if(a.b==ol.proj.get("EPSG:3857"))a.e=new Cesium.WebMercatorTilingScheme;else return;a.l=a.e.rectangle;b=vb(a.a);a.g=null===b?void 0:b;a.f=!0}}
function vb(a){var b="",c=a.getAttributions();null===c||A(c,function(a){b+=a.getHTML().replace(/<\/?[^>]+(>|$)/g,"")+" "});var d,e;0==b.length&&(a=a.getLogo(),n(a)&&(s(a)?d=a:(d=a.src,e=a.href)));return n(d)||0<b.length?new Cesium.Credit(b,d,e):null}Q.prototype.getTileCredits=function(){};Q.prototype.getTileCredits=Q.prototype.getTileCredits;
Q.prototype.requestImage=function(a,b,c){var d=this.a.getTileUrlFunction();if(null===d||null===this.b)return this.d;var e=this.e instanceof Cesium.GeographicTilingScheme?c+1:c;b=this.a.getTileGrid()instanceof ol.tilegrid.XYZ?b:b-(1<<c);a=d([e,a,-b-1],1,this.b);return n(a)?Cesium.ImageryProvider.loadImage(this,a):this.d};Q.prototype.requestImage=Q.prototype.requestImage;function wb(a,b){Cesium.PrimitiveCollection.call(this);var c=new Cesium.BillboardCollection({scene:b}),d=new Cesium.PrimitiveCollection;this.a={projection:a,billboards:c,featureToCesiumMap:{},primitives:d};this.add(c)}w(wb,Cesium.PrimitiveCollection);function xb(a,b,c,d,e){var f=Cesium.Math.clamp,g=Cesium.defaultValue;e=e||{};var h=g(e.duration,500),k=g(e.easing,ol.easing.linear),r=e.callback,G=ga(),D=0,gb=new Cesium.Matrix4,hb=new P(function(e){e=k(f((e-G)/h,0,1));a.transform.clone(gb);var g=(e-D)*b;D=e;a.lookAtTransform(d);a.rotate(c,g);a.lookAtTransform(gb);1>e?hb.start():r&&r()});hb.start()}function yb(a,b){var c=a.camera.getPickRay(b);return a.globe.pick(c,a)||a.camera.pickEllipsoid(b)}
function zb(a){var b=a.canvas,b=new Cesium.Cartesian2(b.width/2,b.height/2);return yb(a,b)}function Ab(a,b,c){var d=new Cesium.Cartesian3,e=new Cesium.Cartesian3,f=new Cesium.Cartesian3;Cesium.Cartesian3.normalize(a,d);Cesium.Cartesian3.normalize(b,e);Cesium.Cartesian3.cross(d,e,f);a=Cesium.Cartesian3.dot(d,e);b=Cesium.Cartesian3.magnitude(f);c=Cesium.Cartesian3.dot(c,f);f=Math.atan2(b,a);return 0<=c?f:-f}
function Bb(a,b){var c=a.camera,d=c.frustum.fovy/2,e;e=a.camera;var f=e.direction,g=Cesium.Quaternion.fromAxisAngle(e.right,e.frustum.fovy/2),g=Cesium.Matrix3.fromQuaternion(g),h=new Cesium.Cartesian3;Cesium.Matrix3.multiplyByVector(g,f,h);e=new Cesium.Ray(e.position,h);e=Cesium.Cartesian3.clone(e.direction);Cesium.Cartesian3.negate(e,e);f=new Cesium.Cartesian3;Cesium.Ellipsoid.WGS84.geocentricSurfaceNormal(b,f);g=new Cesium.Cartesian3;Cesium.Cartesian3.negate(c.right,g);return Ab(f,e,g)+d}
function Cb(a,b,c){n(c)&&(c=c.getHeight(b),b.height=n(c)?c:0);c=Cesium.Ellipsoid.WGS84;b=c.cartographicToCartesian(b);var d=a.position,e=new Cesium.Cartesian3;c.geocentricSurfaceNormal(d,e);a.lookAt(d,b,e)}function Db(a,b){if(null===a||null===b)return null;var c=ol.proj.transformExtent(a,b,"EPSG:4326");return Cesium.Rectangle.fromDegrees(c[0],c[1],c[2],c[3])}
function Eb(a,b){if(!(a instanceof ol.layer.Tile))return null;var c=null,c=a.getSource();if(!(c instanceof ol.source.WMTS)&&c instanceof ol.source.TileImage){var d=c.getProjection();if(null===d)d=b;else if(d!==b)return null;var e=d===ol.proj.get("EPSG:3857"),d=d===ol.proj.get("EPSG:4326");if(e||d)c=new Q(c,b);else return null}else return null;e={};d=a.getExtent();null!=d&&null!==b&&(e.rectangle=Db(d,b));return new Cesium.ImageryLayer(c,e)}
function Fb(a,b){var c=a.getOpacity();n(c)&&(b.alpha=c);c=a.getVisible();n(c)&&(b.show=c);c=a.getSaturation();n(c)&&(b.saturation=c);c=a.getContrast();n(c)&&(b.contrast=c);c=a.getBrightness();n(c)&&(b.brightness=Math.pow(1+parseFloat(c),2))}function R(a){return 2<a.length?Cesium.Cartesian3.fromDegrees(a[0],a[1],a[2]):Cesium.Cartesian3.fromDegrees(a[0],a[1])}function Gb(a){for(var b=[],c=0;c<a.length;++c)b.push(R(a[c]));return b}
function S(a,b){var c=ol.proj.get("EPSG:4326"),d=ol.proj.get(b);if(d!==c){var e=a.getProperties();a=a.clone();a.transform(d,c);a.setProperties(e)}return a}function Hb(a){a=a||"black";if(q(a))return new Cesium.Color(Cesium.Color.byteToFloat(a[0]),Cesium.Color.byteToFloat(a[1]),Cesium.Color.byteToFloat(a[2]),a[3]);if(s(a))return Cesium.Color.fromCssColorString(a);y("impossible")};function T(a,b){this.c=a;this.b=a.camera;this.i=b;this.k=this.a=null;this.f=this.d=Ib;this.e=this.g=0;this.h=null;this.l=!1;this.i.on("change:view",function(){this.C(this.i.getView())},this);this.C(this.i.getView())}function Ib(a,b,c){c=c||a.length;if(b)for(var d=0;d<c;++d)b[d]=a[d];return a}l=T.prototype;
l.C=function(a){null!==this.a&&(this.a.unByKey(this.k),this.k=null);this.a=a;if(null===a)this.f=this.d=Ib;else{var b=ol.proj.getTransform(a.getProjection(),"EPSG:4326"),c=ol.proj.getTransform("EPSG:4326",a.getProjection());this.d=b;this.f=c;this.k=a.on("propertychange",this.ea,this);U(this)}};l.ea=function(){this.l||U(this)};l.oa=function(a){null===this.a||this.a.setRotation(a)};l.ga=function(){if(null!==this.a){var a=this.a.getRotation();return n(a)?a:0}};l.pa=function(a){this.g=a;Jb(this)};
l.da=function(){return this.g};l.ma=function(a){this.e=a;Jb(this);this.r()};l.aa=function(){return this.e};l.ja=function(a){null===this.a||this.a.setCenter(a)};l.getCenter=function(){return null===this.a?void 0:this.a.getCenter()};l.ka=function(a){null!==this.d&&(a=this.d(a),a=new Cesium.Cartographic(a[0]*Math.PI/180,a[1]*Math.PI/180,this.Y()),this.b.position=Cesium.Ellipsoid.WGS84.cartographicToCartesian(a),this.r())};
l.ha=function(){if(null!==this.f){var a=Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position);return this.f([180*a.longitude/Math.PI,180*a.latitude/Math.PI])}};l.la=function(a){var b=Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position);b.height=a;this.b.position=Cesium.Ellipsoid.WGS84.cartographicToCartesian(b);this.r()};l.Y=function(){return Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position).height};
l.ia=function(a){null!==this.d&&(a=this.d(a),a=Cesium.Cartographic.fromDegrees(a[0],a[1]),Cb(this.b,a,this.c.globe),this.r())};function Jb(a){if(null!==a.a&&null!==a.d){var b=a.a.getCenter();if(b){b=a.d(b);b=new Cesium.Cartographic(b[0]*Math.PI/180,b[1]*Math.PI/180);if(a.c.globe){var c=a.c.globe.getHeight(b);b.height=n(c)?c:0}a.b.setView({positionCartographic:b,pitch:a.g-Cesium.Math.PI_OVER_TWO,heading:-a.a.getRotation()});a.b.moveBackward(a.e);Kb(a,!0)}}}
function U(a){if(null!==a.a&&null!==a.d){var b=a.a.getCenter();if(null!=b){var c=a.d(b),b=a.a.getResolution(),b=n(b)?b:0,c=c[1]*Math.PI/180,d=a.c.canvas,e=a.b.frustum.fovy,f=a.a.getProjection().getMetersPerUnit();a.e=b*d.height*f*Math.cos(Math.abs(c))/2/Math.tan(e/2);Jb(a)}}}
l.r=function(){if(null!==this.a&&null!==this.f){this.l=!0;var a=Cesium.Ellipsoid.WGS84,b=this.c,c=zb(b),d=c;d||(d=b.globe,b=this.b.positionCartographic.clone(),d=d.getHeight(b),b.height=n(d)?d:0,d=Cesium.Ellipsoid.WGS84.cartographicToCartesian(b));this.e=Cesium.Cartesian3.distance(d,this.b.position);b=a.cartesianToCartographic(d);this.a.setCenter(this.f([180*b.longitude/Math.PI,180*b.latitude/Math.PI]));this.a.setResolution(Lb(this,this.e,b?b.latitude:0));if(c){d=this.b.position;b=new Cesium.Cartesian3;
a.geocentricSurfaceNormal(c,b);a=new Cesium.Cartesian3;Cesium.Cartesian3.subtract(d,c,a);Cesium.Cartesian3.normalize(a,a);var d=this.b.up,e=this.b.right,f=new Cesium.Cartesian3(-c.y,c.x,0),e=Cesium.Cartesian3.angleBetween(e,f),c=Cesium.Cartesian3.cross(c,d,new Cesium.Cartesian3).z;this.a.setRotation(0>c?e:-e);c=Math.acos(Cesium.Cartesian3.dot(b,a));this.g=isNaN(c)?0:c}else this.a.setRotation(this.b.heading),this.g=-this.b.pitch+Math.PI/2;this.l=!1}};
function Kb(a,b){var c=a.b.viewMatrix;a.h&&a.h.equals(c)||(a.h=c.clone(),!0!==b&&a.r())}function Lb(a,b,c){var d=a.c.canvas,e=a.b.frustum.fovy;a=a.a.getProjection().getMetersPerUnit();return 2*b*Math.tan(e/2)/a/Math.cos(Math.abs(c))/d.height};function V(){Ha.call(this);this.u=new N(this);this.k=this}w(V,Ha);V.prototype[M]=!0;V.prototype.removeEventListener=function(a,b,c,d){fb(this,a,b,c,d)};function Mb(a,b){var c=a.k,d=b,e=d.type||d;if(s(d))d=new K(d,c);else if(d instanceof K)d.target=d.target||c;else{var f=d,d=new K(e,c);Sa(d,f)}c=d.a=c;Nb(c,e,!0,d);Nb(c,e,!1,d)}V.prototype.h=function(a,b,c,d){return this.u.add(String(a),b,!1,c,d)};
function Nb(a,b,c,d){if(b=a.u.a[String(b)]){b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.v&&g.F==c){var h=g.p,k=g.G||g.src;g.D&&Ua(a.u,g);e=!1!==h.call(k,d)&&e}}}};function W(a){a=n(a)?a:{};V.call(this);this.b=this.c=null;this.a=new Cesium.RectanglePrimitive({asynchronous:!1,rectangle:new Cesium.Rectangle,material:Cesium.Material.fromType(Cesium.Material.ColorType)});this.a.material.uniforms.color=new Cesium.Color(0,0,1,.5);this.d=n(a.fa)?a.fa:Cesium.KeyboardEventModifier.SHIFT;this.e=null}w(W,V);
W.prototype.l=function(a){var b=this.c.globe.ellipsoid;a=this.c.camera.getPickRay(a.position);a=this.c.globe.pick(a,this.c);n(a)&&(this.b.setInputAction(u(this.f,this),Cesium.ScreenSpaceEventType.MOUSE_MOVE),this.b.setInputAction(u(this.g,this),Cesium.ScreenSpaceEventType.LEFT_UP),n(this.d)&&(this.b.setInputAction(u(this.f,this),Cesium.ScreenSpaceEventType.MOUSE_MOVE,this.d),this.b.setInputAction(u(this.g,this),Cesium.ScreenSpaceEventType.LEFT_UP,this.d)),b=b.cartesianToCartographic(a),a=this.a.rectangle,
a.north=a.south=b.latitude,a.east=a.west=b.longitude,this.a.height=b.height,this.a.show=!0,Mb(this,{type:"boxstart",position:b}),this.c.primitives.contains(this.a)||this.c.primitives.add(this.a),this.c.screenSpaceCameraController.enableInputs=!1,this.e=b)};
W.prototype.f=function(a){var b=this.c.globe.ellipsoid;a=this.c.camera.getPickRay(a.endPosition);a=this.c.globe.pick(a,this.c);n(a)&&(b=b.cartesianToCartographic(a),this.a.height=Math.max(this.a.height,b.height),b.latitude<this.e.latitude?this.a.rectangle.south=b.latitude:this.a.rectangle.north=b.latitude,b.longitude<this.e.longitude?this.a.rectangle.west=b.longitude:this.a.rectangle.east=b.longitude)};
W.prototype.g=function(a){var b=this.c.globe.ellipsoid;a=this.c.camera.getPickRay(a.position);a=this.c.globe.pick(a,this.c);n(a)&&(b=b.cartesianToCartographic(a),this.a.show=!1,Mb(this,{type:"boxend",position:b}),this.b.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP),this.b.removeInputAction(Cesium.ScreenSpaceEventType.MOUSE_MOVE),n(this.d)&&(this.b.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP,this.d),this.b.removeInputAction(Cesium.ScreenSpaceEventType.MOUSE_MOVE,this.d)));this.c.screenSpaceCameraController.enableInputs=
!0};W.prototype.H=function(a){null===a?(this.c.primitives.contains(this.a)&&this.c.primitives.remove(this.a),null!==this.b&&(this.b.destroy(),this.b=null)):(this.b=new Cesium.ScreenSpaceEventHandler(a.canvas),this.b.setInputAction(u(this.l,this),Cesium.ScreenSpaceEventType.LEFT_DOWN,this.d));this.c=a};function X(a){this.scene=a}function Ob(a,b,c,d,e){var f={flat:!0,renderState:{depthTest:{enabled:!0}}};n(e)&&(f.renderState||(f.renderState={}),f.renderState.lineWidth=e);e=new Cesium.PerInstanceColorAppearance(f);c=new Cesium.GeometryInstance({geometry:c,attributes:{color:Cesium.ColorGeometryInstanceAttribute.fromColor(d)}});c=new Cesium.Primitive({geometryInstances:c,appearance:e});c.olLayer=a;c.olFeature=b;return c}
function Pb(a,b){var c=a.getFill()?a.getFill().getColor():null,d=a.getStroke()?a.getStroke().getColor():null,e="black";d&&b?e=d:c&&(e=c);return Hb(e)}function Qb(a,b){var c=b.getStroke()?b.getStroke().getWidth():1;return Math.min(c,a.scene.maximumAliasedLineWidth)}function Rb(a,b,c,d,e,f){var g=Pb(f,!1),h=Pb(f,!0),k=new Cesium.PrimitiveCollection;f.getFill()&&(d=Ob(b,c,d,g),k.add(d));f.getStroke()&&(a=Qb(a,f),d=Ob(b,c,e,h,a),k.add(d));return k}
function Sb(a,b,c,d,e,f){var g;f instanceof Cesium.PrimitiveCollection?g=f:(g=new Cesium.PrimitiveCollection,g.add(f));if(!e.getText())return g;e=e.getText();(a=a.U(b,c,d,e))&&g.add(a);return g}l=X.prototype;l.Q=function(a,b,c,d){a=a.add(b);a.olLayer=c;a.olFeature=d;return a};
l.T=function(a,b,c,d,e){c=S(c,d);d=c.getCenter();var f=3==d.length?d[2]:0,g=d.slice();g[0]+=c.getRadius();d=R(d);var g=R(g),h=Cesium.Cartesian3.distance(d,g),g=new Cesium.CircleGeometry({center:d,radius:h,height:f});d=new Cesium.CircleOutlineGeometry({center:d,radius:h,extrudedHeight:f,height:f});d=Rb(this,a,b,g,d,e);return Sb(this,a,b,c,e,d)};
l.M=function(a,b,c,d,e){c=S(c,d);var f=Gb(c.getCoordinates());d=new Cesium.PolylineMaterialAppearance({material:this.W(0,e,!0)});f=new Cesium.PolylineGeometry({positions:f,width:Qb(this,e),vertexFormat:d.vertexFormat});d=new Cesium.Primitive({geometryInstances:new Cesium.GeometryInstance({geometry:f}),appearance:d});d.olLayer=a;d.olFeature=b;return Sb(this,a,b,c,e,d)};
l.N=function(a,b,c,d,e){c=S(c,d);for(var f=c.getLinearRings(),g=d={},h=0;h<f.length;++h){var k=f[h].getCoordinates(),k=Gb(k);0==h?d.positions=k:(d.holes={positions:k},d=d.holes)}f=new Cesium.PolygonGeometry({polygonHierarchy:g,perPositionHeight:!0});d=new Cesium.PolygonOutlineGeometry({polygonHierarchy:d,perPositionHeight:!0});d=Rb(this,a,b,f,d,e);return Sb(this,a,b,c,e,d)};
l.L=function(a,b,c){c=c.get("altitudeMode");n(c)||(c=b.get("altitudeMode"));n(c)||(c=a.get("altitudeMode"));a=Cesium.HeightReference.NONE;"clampToGround"===c?a=Cesium.HeightReference.CLAMP_TO_GROUND:"relativeToGround"===c&&(a=Cesium.HeightReference.RELATIVE_TO_GROUND);return a};
l.J=function(a,b,c,d,e,f,g){c=S(c,d);var h=e.getImage(),k=h.getImage(1),r=u(function(){if(null!==k&&(k instanceof HTMLCanvasElement||k instanceof Image||k instanceof HTMLImageElement)){var d=c.getCoordinates(),d=R(d),e,r=h.getOpacity();n(r)&&(e=new Cesium.Color(1,1,1,r));r=this.L(a,b,c);e=this.Q(f,{image:k,color:e,heightReference:r,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,position:d},a,b);g&&g(e)}},this);k instanceof Image&&(""==k.src||0==k.naturalHeight||0==k.naturalWidth||!k.complete)?eb(k,"load",
function(){r()}):r();return e.getText()?Sb(this,a,b,c,e,new Cesium.Primitive):null};
l.V=function(a,b,c,d,e,f,g){function h(c,f){var g=new Cesium.PrimitiveCollection;A(c,function(c){g.add(f(a,b,c,d,e))});return g}switch(c.getType()){case "MultiPoint":c=c.getPoints();if(e.getText()){var k=new Cesium.PrimitiveCollection;A(c,function(c){(c=this.J(a,b,c,d,e,f,g))&&k.add(c)}.bind(this));return k}A(c,function(c){this.J(a,b,c,d,e,f,g)});return null;case "MultiLineString":return c=c.getLineStrings(),h(c,this.M.bind(this));case "MultiPolygon":return c=c.getPolygons(),h(c,this.N.bind(this));
default:y("Unhandled multi geometry type"+c.getType())}};
l.U=function(a,b,c,d){var e=d.getText(),f=new Cesium.LabelCollection({scene:this.scene}),g=ol.extent.getCenter(c.getExtent());if(c instanceof ol.geom.SimpleGeometry){var h=c.getFirstCoordinate();g[2]=3==h.length?h[2]:0}h={};h.position=R(g);h.text=e;h.heightReference=this.L(a,b,c);c=d.getOffsetX();e=d.getOffsetY();0!=c&&0!=e&&(c=new Cesium.Cartesian2(c,e),h.pixelOffset=c);c=d.getFont();null!=c&&(h.font=c);c=void 0;d.getFill()&&(h.fillColor=Pb(d,!1),c=Cesium.LabelStyle.FILL);d.getStroke()&&(h.outlineWidth=
Qb(this,d),h.outlineColor=Pb(d,!0),c=Cesium.LabelStyle.OUTLINE);d.getFill()&&d.getStroke()&&(c=Cesium.LabelStyle.FILL_AND_OUTLINE);h.style=c;if(d.getTextAlign()){var k;switch(d.getTextAlign()){case "center":k=Cesium.HorizontalOrigin.CENTER;break;case "left":k=Cesium.HorizontalOrigin.LEFT;break;case "right":k=Cesium.HorizontalOrigin.RIGHT;break;default:y("unhandled text align "+d.getTextAlign())}h.horizontalOrigin=k}if(d.getTextBaseline()){var r;switch(d.getTextBaseline()){case "top":r=Cesium.VerticalOrigin.TOP;
break;case "middle":r=Cesium.VerticalOrigin.CENTER;break;case "bottom":r=Cesium.VerticalOrigin.BOTTOM;break;case "alphabetic":r=Cesium.VerticalOrigin.TOP;break;case "hanging":r=Cesium.VerticalOrigin.BOTTOM;break;default:y("unhandled baseline "+d.getTextBaseline())}h.verticalOrigin=r}d=f.add(h);d.olLayer=a;d.olFeature=b;return f};
l.W=function(a,b,c){a=b.getFill();b=b.getStroke();if(c&&!b||!c&&!a)return null;a=c?b.getColor():a.getColor();a=Hb(a);return c&&b.getLineDash()?Cesium.Material.fromType("Stripe",{horizontal:!1,repeat:500,evenColor:a,oddColor:new Cesium.Color(0,0,0,0)}):Cesium.Material.fromType("Color",{color:a})};l.K=function(a,b,c,d){a=b.getStyleFunction();var e;n(a)&&(e=a.call(b,d));null==e&&null!=c&&(e=c(b,d));return n(e)?e[0]:null};
l.I=function(a,b,c,d,e){function f(a){d.featureToCesiumMap[t(b)]=a}e=e||b.getGeometry();var g=d.projection;if(!e)return null;switch(e.getType()){case "GeometryCollection":var h=new Cesium.PrimitiveCollection;A(e.getGeometries(),function(e){e&&(e=this.I(a,b,c,d,e))&&h.add(e)}.bind(this));return h;case "Point":return(e=this.J(a,b,e,g,c,d.billboards,f))?e:null;case "Circle":return this.T(a,b,e,g,c);case "LineString":return this.M(a,b,e,g,c);case "Polygon":return this.N(a,b,e,g,c);case "MultiPoint":case "MultiLineString":case "MultiPolygon":return(e=
this.V(a,b,e,g,c,d.billboards,f))?e:null;case "LinearRing":throw Error("LinearRing should only be part of polygon.");default:throw Error("Ol geom type not handled : "+e.getType());}};l.X=function(a,b,c){var d=a.getSource().getFeatures(),e=b.getProjection();b=b.getResolution();if(!n(b)||!e)throw y("View not ready"),Error("View not ready");for(var e=new wb(e,this.scene),f=e.a,g=0;g<d.length;++g){var h=d[g];if(null!=h){var k=a.getStyleFunction();if(k=this.K(0,h,k,b))if(k=this.I(a,h,k,f))c[t(h)]=k,e.add(k)}}return e};
l.P=function(a,b,c,d){var e=b.getProjection();b=b.getResolution();if(!n(b)||!e)return null;var f=a.getStyleFunction();b=this.K(0,c,f,b);if(!b)return null;d.projection=e;return this.I(a,c,b,d)};var Tb=!E||E&&9<=Ea;!F&&!E||E&&E&&9<=Ea||F&&J("1.9.1");E&&J("9");var tb="CANVAS";function Ub(a){var b=document;return s(a)?b.getElementById(a):a}
function Vb(a){var b=a||document,c=null;if(b.querySelectorAll&&b.querySelector)c=b.querySelector(".ol-overlaycontainer");else{var d,b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".ol-overlaycontainer");else if(a.getElementsByClassName){var e=a.getElementsByClassName("ol-overlaycontainer");a=e}else{e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className,g;if(g="function"==typeof f.split)g=0<=z.indexOf.call(f.split(/\s+/),"ol-overlaycontainer",void 0);
g&&(d[c++]=a)}d.length=c;a=d}c=a[0]}return c||null}function Wb(a,b){Na(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Xb?a.setAttribute(Xb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Xb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Yb(a,b,c){var d=arguments,e=document,f=d[0],g=d[1];if(!Tb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ia(g.name),'"');if(g.type){f.push(' type="',ia(g.type),'"');var h={};Sa(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(s(g)?f.className=g:q(g)?f.className=g.join(" "):Wb(f,g));2<d.length&&Zb(e,f,d);return f}
function Zb(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!aa(f)||ba(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ba(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==p(f)){g="function"==typeof f.item;break a}}g=!1}A(g?ta(f):f,d)}}}function $b(a){if(void 0!=a.nextElementSibling)a=a.nextElementSibling;else for(a=a.nextSibling;a&&1!=a.nodeType;)a=a.nextSibling;return a};function Y(a,b){this.t=b.imageryLayers;this.B=new Cesium.ImageryLayerCollection;O.call(this,a,b)}w(Y,O);Y.prototype.l=function(a){this.t.add(a);this.B.add(a)};Y.prototype.S=function(a){a.destroy()};Y.prototype.k=function(a){for(var b=0;b<this.B.length;++b)this.t.remove(this.B.get(b),a);this.B.removeAll(!1)};
Y.prototype.R=function(a){if(!(a instanceof ol.layer.Tile))return null;var b=this.e.getProjection(),c=Eb(a,b);null!==c&&(a.on("change:brightness change:contrast change:hue change:opacity change:saturation change:visible".split(" "),function(){null===c||Fb(a,c)}),Fb(a,c),a.on("change:extent",function(){this.t.remove(c,!0);this.B.remove(c,!1);delete this.o[t(a)];this.q()},this),a.on("change",function(){var a=this.t.indexOf(c);0<=a&&(this.t.remove(c,!1),this.t.add(c,a))},this));return c};function Z(a,b,c){this.H=c||new X(b);this.a=new Cesium.PrimitiveCollection;b.primitives.add(this.a);this.a.destroyPrimitives=!1;O.call(this,a,b)}w(Z,O);Z.prototype.l=function(a){this.a.add(a)};Z.prototype.S=function(a){a.destroy()};Z.prototype.k=function(a){this.a.destroyPrimitives=a;this.a.removeAll();this.a.destroyPrimitives=!1};
Z.prototype.R=function(a){if(!(a instanceof ol.layer.Vector))return null;var b=this.e,c=a.getSource(),d={},e=this.H.X(a,b,d);a.on("change:visible",function(){e.show=a.getVisible()});var f=u(function(c){var f=this.H.P(a,b,c,e.a);f&&(d[t(c)]=f,e.add(f))},this),g=u(function(a){var b=a.getGeometry();a=t(a);if(null!=b&&"Point"==b.getType()){var b=e.a,c=b.billboards,f=b.featureToCesiumMap[a];delete b.featureToCesiumMap[a];null!=f&&c.remove(f)}b=d[a];delete d[a];null!=b&&e.remove(b)},this);c.on("addfeature",
function(a){f(a.feature)},this);c.on("removefeature",function(a){g(a.feature)},this);c.on("changefeature",function(a){a=a.feature;g(a);f(a)},this);return e};function $(a){this.i=a.map;this.b=Yb("DIV",{style:"position:absolute;top:0;left:0;width:100%;height:100%;visibility:hidden;"});var b=Ub(a.target||null);if(b)b.appendChild(this.b);else{var c=this.i.getViewport();(c=Vb(c))&&c.parentNode&&c.parentNode.insertBefore(this.b,c)}this.d=null==b;this.j=Yb(tb,{style:"position:absolute;top:0;left:0;width:100%;height:100%;"});this.j.oncontextmenu=function(){return!1};this.j.onselectstart=function(){return!1};this.b.appendChild(this.j);this.n=!1;this.O=[];this.a=
null;this.c=new Cesium.Scene({canvas:this.j,scene3DOnly:!0});b=this.c.screenSpaceCameraController;b.inertiaSpin=0;b.ineartiaTranslate=0;b.inertiaZoom=0;b.tiltEventTypes.push({eventType:Cesium.CameraEventType.LEFT_DRAG,modifier:Cesium.KeyboardEventModifier.SHIFT});b.tiltEventTypes.push({eventType:Cesium.CameraEventType.LEFT_DRAG,modifier:Cesium.KeyboardEventModifier.ALT});b.enableLook=!1;this.c.camera.constrainedAxis=Cesium.Cartesian3.UNIT_Z;this.s=new T(this.c,this.i);this.e=new Cesium.Globe(Cesium.Ellipsoid.WGS84);
this.c.globe=this.e;this.c.skyAtmosphere=new Cesium.SkyAtmosphere;a=n(a.createSynchronizers)?a.createSynchronizers(this.i,this.c):[new Y(this.i,this.c),new Z(this.i,this.c)];for(b=a.length-1;0<=b;--b)a[b].q();this.d&&(a=$b(this.j),null!=a&&(a.style.display="none"));U(this.s);this.A=new P(function(){this.c.initializeFrame();var a=this.j.clientWidth,b=this.j.clientHeight;if(this.j.width!==a||this.j.height!==b)this.j.width=a,this.j.height=b,this.c.camera.frustum.aspectRatio=a/b;this.c.render();this.n&&
Kb(this.s);this.A.start()},void 0,this)}l=$.prototype;l.Z=function(){return this.s};l.ca=function(){return this.i};l.$=function(){return this.c};l.ba=function(){return this.n};
l.na=function(a){if(this.n!=a)if(this.n=a,this.b.style.visibility=this.n?"visible":"hidden",this.n){if(this.d){var b=this.i.getInteractions();b.forEach(function(a){this.O.push(a)},this);b.clear();a=this.i.getLayerGroup();a.getVisible()&&(this.a=a,this.a.setVisible(!1))}U(this.s);this.A.start()}else this.d&&(b=this.i.getInteractions(),A(this.O,function(a){b.push(a)},this),this.O.length=0,null!==this.a&&(this.a.setVisible(!0),this.a=null)),this.s.r(),qb(this.A)};
l.ra=function(a,b){if(!this.n){U(this.s);var c=this.e.ellipsoid,d=this.c.camera,e=c.cartesianToCartographic(d.position);e.height<a&&(e.height=a,d.position=c.cartographicToCartesian(e));this.A.start();var f=this;setTimeout(function(){!f.n&&qb(f.A)},b)}};v("olcs.AbstractSynchronizer",O);O.prototype.synchronize=O.prototype.q;v("olcs.Camera",T);T.prototype.setHeading=T.prototype.oa;T.prototype.getHeading=T.prototype.ga;T.prototype.setTilt=T.prototype.pa;T.prototype.getTilt=T.prototype.da;T.prototype.setDistance=T.prototype.ma;T.prototype.getDistance=T.prototype.aa;T.prototype.setCenter=T.prototype.ja;T.prototype.getCenter=T.prototype.getCenter;T.prototype.setPosition=T.prototype.ka;T.prototype.getPosition=T.prototype.ha;T.prototype.setAltitude=T.prototype.la;
T.prototype.getAltitude=T.prototype.Y;T.prototype.lookAt=T.prototype.ia;T.prototype.updateView=T.prototype.r;v("olcs.core.computePixelSizeAtCoordinate",function(a,b){var c=a.camera,d=a.canvas,e=c.frustum,d=new Cesium.Cartesian2(d.width,d.height),c=Cesium.Cartesian3.magnitude(Cesium.Cartesian3.subtract(c.position,b,new Cesium.Cartesian3));return e.getPixelSize(d,c)});
v("olcs.core.applyHeightOffsetToGeometry",function(a,b){a.applyTransform(function(a,d,e){if(n(e)&&3<=e)for(a=0;a<d.length;a+=e)d[a+2]+=b;return d})});v("olcs.core.rotateAroundAxis",xb);
v("olcs.core.setHeadingUsingBottomCenter",function(a,b,c){var d=a.camera;a=Bb(a,c);a=Cesium.Quaternion.fromAxisAngle(d.right,a);var e=Cesium.Matrix3.fromQuaternion(a),f=new Cesium.Cartesian3;Cesium.Cartesian3.subtract(d.position,c,f);a=new Cesium.Cartesian3;Cesium.Matrix3.multiplyByVector(e,f,a);Cesium.Cartesian3.add(a,c,a);c=Cesium.Matrix4.fromTranslation(a);xb(d,b,a,c)});v("olcs.core.pickOnTerrainOrEllipsoid",yb);
v("olcs.core.pickBottomPoint",function(a){var b=a.canvas,b=new Cesium.Cartesian2(b.width/2,b.height);return yb(a,b)});v("olcs.core.pickCenterPoint",zb);
v("olcs.core.computeSignedTiltAngleOnGlobe",function(a){var b=a.camera,c=new Cesium.Ray(b.position,b.direction);a=a.globe.pick(c,a);if(!a){var d=Cesium.IntersectionTests.rayEllipsoid(c,Cesium.Ellipsoid.WGS84);d&&(a=Cesium.Ray.getPoint(c,d.start))}if(a)return c=new Cesium.Cartesian3,Cesium.Ellipsoid.WGS84.geocentricSurfaceNormal(a,c),b=Ab(b.direction,c,b.right)-Math.PI,Cesium.Math.convertLongitudeRange(b)});v("olcs.core.computeAngleToZenith",Bb);v("olcs.core.lookAt",Cb);
v("olcs.core.extentToRectangle",Db);v("olcs.core.tileLayerToImageryLayer",Eb);v("olcs.core.updateCesiumLayerProperties",Fb);v("olcs.core.ol4326CoordinateToCesiumCartesian",R);v("olcs.core.ol4326CoordinateArrayToCsCartesians",Gb);v("olcs.core.olGeometryCloneTo4326",S);v("olcs.core.convertColorToCesium",Hb);v("olcs.DragBox",W);W.prototype.setScene=W.prototype.H;W.prototype.listen=W.prototype.h;v("olcs.FeatureConverter",X);X.prototype.csAddBillboard=X.prototype.Q;
X.prototype.olCircleGeometryToCesium=X.prototype.T;X.prototype.olLineStringGeometryToCesium=X.prototype.M;X.prototype.olPolygonGeometryToCesium=X.prototype.N;X.prototype.getHeightReference=X.prototype.L;X.prototype.olPointGeometryToCesium=X.prototype.J;X.prototype.olMultiGeometryToCesium=X.prototype.V;X.prototype.olGeometry4326TextPartToCesium=X.prototype.U;X.prototype.olStyleToCesium=X.prototype.W;X.prototype.computePlainStyle=X.prototype.K;X.prototype.olFeatureToCesium=X.prototype.I;
X.prototype.olVectorLayerToCesium=X.prototype.X;X.prototype.convert=X.prototype.P;v("olcs.OLCesium",$);$.prototype.getCamera=$.prototype.Z;$.prototype.getOlMap=$.prototype.ca;$.prototype.getCesiumScene=$.prototype.$;$.prototype.getEnabled=$.prototype.ba;$.prototype.setEnabled=$.prototype.na;$.prototype.warmUp=$.prototype.ra;v("olcs.RasterSynchronizer",Y);v("olcs.VectorSynchronizer",Z);})();
